In [6]:
import numpy as np

In [7]:
# Parameters
dim_n = 10
dim_p = 20

sigma_sq = 1**2

In [8]:
X = np.random.normal(0, 1, (dim_n, dim_p))
beta = np.ones(dim_p)
Y = np.zeros(dim_n)

np.matmul(X, beta, out=Y) + np.random.normal(0, np.sqrt(sigma_sq), dim_n)

Y

array([-7.42046077, -1.67366922,  4.17559595,  1.33907247,  3.98078213,
       -3.17634563, -1.30762014, -4.50943662,  4.32922817, -6.33410021])

In [24]:
# See http://statweb.stanford.edu/~tibs/ftp/lars.pdf, page 7
# Step 2: Let mathcal A be the active set indexing the covariances in c that are maximal in absolute value
def get_mathcal_A_step2(c):
    max_covariate = np.max(np.abs(c))
    return list(np.argwhere(np.abs(c) == max_covariate).flatten())

# Step 2: Let B be the set indexing the non-zero coefficients of beta
def get_mathcal_B_step2(beta):
    return list(np.argwhere(beta != 0).flatten())

# Let sA be the vector containing the signs of those covariances
def get_s_mathcal_A(c, mathcal_A):
    return np.sign(c[mathcal_A])

# write SA for the diagonal matrix whose diagonal is given by sA
def get_S_mathcal_A(c, mathcal_A):
    return np.diag(get_s_mathcal_A(c, mathcal_A))

def get_X_(X, mathcal):
    return X[:, mathcal]

def get_SAXATX(X, c, mathcal_A):
    SA = get_S_mathcal_A(c, mathcal_A)
    XAT = get_X_(X, mathcal_A).T
    
    return np.matmul(np.matmul(SA, XAT), X)

In [26]:
# DASSO algorithm

dim_n = X.shape[0]
dim_p = beta.shape[0]

# Step 1
beta = np.zeros(dim_p)
beta[3] = 1
l = 1
c = np.zeros(dim_p)

# while True:

# Step 2
mathcal_B = get_mathcal_B_step2(beta)

np.matmul(X.T, (Y - np.matmul(X, beta)), out=c)
mathcal_A = get_mathcal_A_step2(c)

sA = get_s_mathcal_A(c, mathcal_A)

# assert len(mathcal_A) == (len(mathcal_B) + 1)

# Step 3
if (len(mathcal_B) == 0):
    mathcal_B.append(get_mathcal_A_step2(c)[0])
else:
    # Appendix 1, step 1
    A = -1 * get_SAXATX(X, c, mathcal_A)
    A = np.append(A, get_SAXATX(X, c, mathcal_A), axis=1)
    A = np.append(A, np.identity(len(mathcal_A)), axis=1)
    
    # Appendix 1, step 2
    


# Step 4

A = -1 * get_SAXATX(X, c, mathcal_A)
A = np.append(A, get_SAXATX(X, c, mathcal_A), axis=1)
A = np.append(A, np.identity(len(mathcal_A)), axis=1)
print(A)

print(mathcal_A, mathcal_B, get_S_mathcal_A(c, mathcal_A))
    
    # Step 5
#     if np.linalg.norm(c, ord=np.inf) == 0:
#         break

[[ -3.89504823  -0.69786547   2.8982338   -3.65116458   0.09432644
   -6.4526732   -4.632906     1.9235436    4.75676615  -1.24327949
    4.71260704  -3.93023496  -5.74617499   0.32240216  -3.81351916
  -17.85856486   1.63540874  -5.03631047  -2.58183157  -3.89854758
    3.89504823   0.69786547  -2.8982338    3.65116458  -0.09432644
    6.4526732    4.632906    -1.9235436   -4.75676615   1.24327949
   -4.71260704   3.93023496   5.74617499  -0.32240216   3.81351916
   17.85856486  -1.63540874   5.03631047   2.58183157   3.89854758
    1.        ]]
[15] [3] [[1.]]


In [31]:
np.maximum(beta, 0)

array([0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

In [98]:
np.abs(c)

array([13.62456136, 21.81697491,  3.44344192,  2.47055399, 23.9931803 ,
        1.56838271, 13.40552802,  8.8610178 ,  0.41188566,  4.56459017,
        0.75183328,  9.19599532,  6.66784077,  6.95675744,  3.64021054,
        5.7824355 ,  4.3870639 ,  0.31045025,  2.94397741, 21.89915234])